### ISSUE TITLE
Color Space "bleaching"

### ISSUE THREAD

**Issue by dspstanky** [dspstanky/pixel-art#2]
While images, display and window capture sources work as expected, some video capture sources i.e. HDX60 capture card have a "bleaching" effect on first two levels of downscale while set to color spaces that should be supported. Need to do some testing and research to figure out why, though ultimately impact is low since not many would use the first two levels of downscale for something like a capture card.

**Comment by andilippi** [comment]
This seems to happen when using @exeldro [Source Clone plugin](https://github.com/exeldro/obs-source-clone) too.

I have also tested with 2 different webcams and the bleaching effect happens on both. However if I add the filter to the scene it works fine. It is just on the actual input source.

**Comment by dspstanky** [comment]
Oh interesting, I couldn't reproduce the issue with my webcams so I missed that, thank you for the report. I'll focus on this issue for now then and try to get an updated release out when I can.

**Comment by JDDoesDev** [comment]
Can confirm @andilippi's findings.  I'm unable to use on a camera or cloned cam source because of the bleaching.  It also seems to have trailing.  I will try to capture some screenshots for examples.

**Comment by JDDoesDev** [comment]
![image](https://github.com/dspstanky/pixel-art/assets/9932557/9e62e6b3-0496-42ce-97c7-aa575194ed88)

**Comment by dspstanky** [comment]
Well as an update, I do have a fix ready for this, (it was a case of forgetting to revert a test change so it was pretty simple), but unfortunately there's currently an issue with a dependency preventing me from creating a release, I'll keep seeing if I can get a workaround to build correctly to get a release out today, but we might be waiting until the dependency issue is cleared up first.

**Comment by dspstanky** [comment]
Fixed with release 0.0.4! If the issue crops up again (potentially on a source I didn't think to test or in tandem with other plugins), please comment so I can take another look, but the code responsible was so ubiquitous I don't think it will be an issue again.
